name: Generate Snake Graph

on:
  schedule: # Har din ek dafa run hoga
    - cron: "0 0 * * *"
  workflow_dispatch: # manually run karne ka option bhi milega

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate Snake animation
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: IsrarSoomro60
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
